<div class="content-wrapper">

  <section class="content-header">
     <h1>Edit Revenue/Expense Item </h1>
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('internal_cost_plan') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Internal Cost Plan Item</li>
    </ol>
  </section>

  <br>




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 

       <!-- Main content -->
    <section class="content">

    <div class="row">
      <div class="col-md-12 col-xs-12">

        <div id="messages"></div>

        <?php if($this->session->flashdata('success')): ?>
          <!--<div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('success'); ?>
          </div>--> 
        <?php elseif($this->session->flashdata('error')): ?>
          <div class="alert alert-error alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('error'); ?>
          </div>
        <?php endif; ?>

        <div class="tab-content">




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                        Internal Cost Plan                                       -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->        




      <div class="box">
          <form role="form" action="<?php base_url('internal_cost_plan/update') ?>" method="post" enctype="multipart/form-data">
              <div class="box-body">

                <?php echo validation_errors(); ?>  

                <div class="row">
                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="edit_budget_type">Budget Type <font color="red">*</font></label>
                      <input type="text" class="form-control" name="edit_budget_type" value="<?php foreach($billing_item as $k => $v){if($icp_item_data['billing_item_id'] == $v['id'] && $v['type']=="0"){echo "Revenue"; break;}else{echo"Expense"; break;}} ?>" READONLY>
                    </div>
                  </div>
                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="edit_billing_item">Item Name<font color="red">*</font></label>
                      <input type="text" class="form-control"  value="<?php foreach($billing_item as $k => $v){if($icp_item_data['billing_item_id'] == $v['id']){echo $v['name'];}} ?>" READONLY>
                      <input type="hidden" class="form-control" name="edit_billing_item" value="<?php foreach($billing_item as $k => $v){if($icp_item_data['billing_item_id'] == $v['id']){echo $v['id'];}} ?>" READONLY>
                    </div>
                  </div>                                                  
                </div>  
                <br>
                <div class="row">
                  <div class="col-md-6 col-xs-6">
                    <div class="form-group">
                      <label for="item_description">Item Description<font color="red">*</font></label>
                      <textarea type="text" class="form-control" id="item_description" name="item_description" autocomplete="off" rows="2" READONLY><?php foreach($billing_item as $k => $v){if($icp_item_data['billing_item_id'] == $v['id']){echo $v['description'];}} ?></textarea>
                    </div>
                  </div>
                </div> 
                <br>             
                <div class="row">  
                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="edit_p_amount">Estimated Amount $JMD</label>
                      <input type="number" class="form-control" id="edit_p_amount" name="edit_p_amount" autocomplete="off" value="<?php foreach($billing_item as $k => $v){if($icp_item_data['billing_item_id'] == $v['id']){echo $v['cost'];}} ?>" READONLY>
                    </div>
                  </div>
                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="edit_a_amount">Actual Amount $JMD</label>
                      <input type="number" class="form-control" id="edit_a_amount" name="edit_a_amount" autocomplete="off" value="<?php echo set_value('edit_a_amount', isset($icp_item_data['a_amount']) ? $icp_item_data['a_amount'] : ''); ?>">
                    </div>
                  </div>
         
                </div>  
                
              </div>    <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Save Changes</button>
                <a href="<?php echo base_url('technical_advice/update/'.$icp_item_data['ta_id']) ?>" class="btn btn-warning">Close</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>


<!------------------------------------------------------------->
<!-- Javascript part of Program                                --->
<!------------------------------------------------------------->

<script type="text/javascript">  

var base_url = "<?php echo base_url(); ?>";    
$(document).ready(function(){

});
    

</script>




