
<div class="content-wrapper">

<section class="content-header">
    <h1>Add New Client - <?php echo $client_data['companyName']; ?> (<?php echo $client_data['trn']; ?>)</h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo base_url('client') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Pending Client(s)</li>
    </ol>
</section>


<?php $active_tab='client'; ?>


<!----------------------------------------------------------------------------------------------------->
<!--                                                                                                 -->
<!--                                       Tab section                                               -->
<!--                                                                                                 -->
<!----------------------------------------------------------------------------------------------------->



<section class="content">
  <ul class="nav nav-tabs">
    <li class="<?php echo (($active_tab === 'client') ? 'active' : '') ?>"><a data-toggle="tab" href="#client">Client</a></li>
    <li class="<?php echo (($active_tab === 'requirement') ? 'active' : '') ?>"><a data-toggle="tab" href="#requirement">Requirement Question(s)</a></li>		
    <li class="<?php echo (($active_tab === 'document') ? 'active' : '') ?>"><a data-toggle="tab" href="#document">Document</a></li>
  </ul>	




<!----------------------------------------------------------------------------------------------------->
<!--                                                                                                 -->
<!--                             Error messages generated by the submit                              -->
<!--                                                                                                 -->
<!----------------------------------------------------------------------------------------------------->


    <div class="row">
        <div class="col-md-12 col-xs-12">

            <div id="messages"></div>

            <?php if($this->session->flashdata('success')): ?>
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <?php echo $this->session->flashdata('success'); ?>
                </div>
            <?php elseif($this->session->flashdata('error')): ?>
                <div class="alert alert-error alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <?php echo $this->session->flashdata('error'); ?>
                </div>
            <?php elseif($this->session->flashdata('warning')): ?>
                <div class="alert alert-warning alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <?php echo $this->session->flashdata('warning'); ?>
                </div>
            <?php endif; ?>

            <div class="tab-content">


<!----------------------------------------------------------------------------------------------------->
<!--                                                                                                 -->
<!--                                        Session variables                                        -->
<!--                                                                                                 -->
<!----------------------------------------------------------------------------------------------------->


    <!-- Creation of a session field to keep the client, register id and the directory -->
    <?php $this->session->unset_userdata('client_id');?>
    <?php if(empty($this->session->userdata('client_id'))) {
        $client_id = array('client_id' => $client_data['id']);
        $this->session->set_userdata($client_id);} ?>

<!----------------------------------------------------------------------------------------------------->
<!--                                                                                                 -->
<!--                                        C L I E N T                                              -->
<!--                                                                                                 -->
<!----------------------------------------------------------------------------------------------------->


<div id="client" class="tab-pane fade <?php echo (($active_tab === 'client') ? 'in active' : '') ?>">	


<div class="box">
            <form role="form" action="<?php base_url('pending_client/addClient') ?>" method="post" enctype="multipart/form-data">

            <div class="box-body">

                <?php echo validation_errors(); ?>

                <!-- /row divide by 3-->
                <div class="row">
                    
                     <div class="col-md-2 col-xs-2">
                        <div class="form-group">
                            <label for="trn">TRN <font color="red">*</font></label>
                            <input type="text" class="form-control" id="trn" name="trn" autocomplete="off"
                            value="<?php echo set_value('trn', isset($client_data['trn']) ? $client_data['trn'] : ''); ?>" readonly/>
                            <!-- <input type="hidden" id="directory" name="directory" value=<?php echo $client_data['directory']; ?> /> -->
                         </div>
                     </div>

                     <div class="col-md-5 col-xs-5">
                        <div class="form-group">
                            <label for="company_name">Company Name <font color="red">*</font></label>
                            <input type="text" class="form-control" id="company_name" name="company_name" autocomplete="off"
                            value="<?php echo set_value('companyName', isset($client_data['companyName']) ? $client_data['companyName'] : ''); ?>" readonly/>
                        </div>
                    </div>

                    <div class="col-md-3 col-xs-3">
                        <div class="form-group">
                            <label for="client_name">Client Name <font color="red">*</font></label>
                            <input type="text" class="form-control" id="clientName" name="clientName" autocomplete="off"
                            value="<?php echo set_value('clientName', isset($client_data['clientName']) ? $client_data['clientName'] : ''); ?>" readonly/>
                        </div>
                    </div>

                    <div class="col-md-2 col-xs-2" align="center">
                        <div class="radio">
                          <label><input type="radio" name="active" id="active" class="" <?php if($client_data['active']=='1') echo "checked='checked'"; ?> value="1" <?php echo $this->form_validation->set_radio('active', 1); ?> />Active&nbsp;&nbsp;&nbsp;&nbsp;</label>
                          <label><input type="radio" name="active" id="active" class="" <?php if($client_data['active']=='2') echo "checked='checked'"; ?> value="2" <?php echo $this->form_validation->set_radio('active', 2); ?> />Inactive</label>
                        </div>
                      </div>

                </div>
                <!-- /end row divide by 4-->


                <!-- /row divide by 4-->
                <div class="row">

                    <div class="col-md-3 col-xs-3">
                        <div class="form-group">
                            <label for="address">Address <font color="red">*</font></label>
                            <input type="text" class="form-control" id="address" name="clientAddress"
                            value="<?php echo set_value('clientAddress', isset($client_data['clientAddress']) ? $client_data['clientAddress'] : ''); ?>"  autocomplete="off" readonly/>
                        </div>
                    </div>

                    <div class="col-md-3 col-xs-3">
                        <div class="form-group">
                            <label for="county">County <font color="red">*</font></label>
                            <input type="text" class="form-control" id="county" name="clientCounty"
                            value="<?php echo set_value('clientCounty', isset($client_data['clientCounty']) ? $client_data['clientCounty'] : ''); ?>"  autocomplete="off" readonly/>
                        </div>
                    </div>

                    <div class="col-md-3 col-xs-3">
                        <div class="form-group">
                            <label for="parish">Parish <font color="red">*</font></label>
                            <input type="text" class="form-control" id="parish" name="clientParish"
                            value="<?php echo set_value('clientParish', isset($client_data['clientParish']) ? $client_data['clientParish'] : ''); ?>"  autocomplete="off" readonly/>
                        </div>
                    </div>

                    <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                        <label for="city">City</label>
                        <input type="text" class="form-control" id="city" name="clientCity"
                        value="<?php echo set_value('clientCity', isset($client_data['clientCity']) ? $client_data['clientCity'] : ''); ?>"  autocomplete="off" readonly/>
                     </div>
                 </div>
            </div>
                <!-- /end row divide by 4-->


            <!-- /row divide by 4-->
            <div class="row">
            <div class="col-md-3 col-xs-3">
                <div class="form-group">
                    <label for="phone">Phone</label>
                    <input type="text" class="form-control" id="phone" name="clientContact" autocomplete="off"
                    value="<?php echo set_value('clientContact', isset($client_data['clientContact']) ? $client_data['clientContact'] : ''); ?>" readonly/>
                </div>
            </div>		
             <div class="col-md-3 col-xs-3">
                <div class="form-group">
                    <label for="email">Email <font color="red">*</font></label>
                    <input type="text" class="form-control" id="email" name="clientEmail" autocomplete="off"
                value="<?php echo set_value('clientEmail', isset($client_data['clientEmail']) ? $client_data['clientEmail'] : ''); ?>" readonly/>
                </div>
            </div>
             <div class="col-md-3 col-xs-3">
                <div class="form-group">
                    <label for="website">Website</label>
                        <input type="text" class="form-control" id="website" name="clientWebsite" autocomplete="off"
                        value="<?php echo set_value('clientWebsite', isset($client_data['clientWebsite']) ? $client_data['clientWebsite'] : ''); ?>" readonly/>
                    </div>
                </div>
            </div>
                <!-- /end row divide by 4-->


            <!-- /row divide by 3-->
                <!-- /end row divide by 3-->

            </div> <!-- /end box -->

            <div class="box-footer">
                <div class="row">
                      <div class="col-md-6 col-xs-6">
                           <?php if(in_array('updateConsultation', $user_permission)): ?>   <!-- you must have the permission to update with the Save button -->   
                              <button type="submit" class="btn btn-primary">Add Client</button>
                         <?php endif; ?>

                        <?php echo '<a href="'.base_url('report_client/REP0C/'.$client_data['id']).'" target="_blank" class="btn btn-success"><i class="fa fa-print"></i></a>'; ?>
                        <a href="<?php echo base_url('pending_client/') ?>" class="btn btn-warning">Close</a>
                    </div>	
                </div>
            </div>
        </form>
    </div>
</div>


<!--Javascript for Client--->


<script type="text/javascript">

$(document).ready(function() {
    $(".select_group").select2({width: '100%'});
    //$("#remark").wysihtml5();
    $("#mainClientNav").addClass('active');
    //$("#manageClientNav").addClass('active');

});
</script>



<!----------------------------------------------------------------------------------------------------->
<!--                                                                                                 -->
<!--                                        R E Q U I R E M E N T                                    -->
<!--                                                                                                 -->
<!----------------------------------------------------------------------------------------------------->


<div id="requirement" class="tab-pane fade <?php echo (($active_tab === 'requirement') ? 'in active' : '') ?>">	

    <div class="row">
        <div class="col-md-12 col-xs-12">
            <div class="box">
                <div class="box-body">
                    <table id="manageTableConsultation" class="table table-bordered table-striped" style="width:100%">
                        <thead>
                            <tr>
                                <th>Question</th>
                                <th>Response(s)</th>
                                <?php if(in_array('viewPendingClient', $user_permission)): ?>
                                <th>Action</th>
                                <?php endif; ?>
                            </tr>
                        </thead>
                    </table>

                </div>
             </div>
        </div>
    </div>
</div>


<!------------------------------------->
<!-- Javascript part of Requirements--->
<!------------------------------------->

<script type="text/javascript">
var manageTableConsultation;
var base_url = "<?php echo base_url(); ?>";

$(document).ready(function() {

$("#consultationClientNav").addClass('active');


// initialize the datatable
manageTableConsultation = $('#manageTableConsultation').DataTable({
    'ajax': base_url+'pending_client/fetchPendingQuestions/'+<?php echo $client_data['trn']; ?>,
    // 'order': [[0, 'asc']]
});

});

</script>

<!----------------------------------------------------------------------------------------------------->
<!--                                                                                                 -->
<!--                                        D O C U M E N T                                         -->
<!--                                                                                                 -->
<!----------------------------------------------------------------------------------------------------->


<div id="document" class="tab-pane fade <?php echo (($active_tab === 'document') ? 'in active' : '') ?>">	

        <div class="box">
            <div class="box-body">
                <div class="row">
                    <div class="col-md-12 col-xs-12">
                        <div class="col-md-12 col-xs-12">
                            <table id="manageTableDocument" class="table table-bordered table-striped" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>Document</th>
                                    </tr>
                                </thead>
                            </table>
                    </div>
                </div>
            </div>

            <div class="box-footer">

                    <a href="<?php echo base_url('pending_client/') ?>" class="btn btn-warning">Close</a>
            </div>

        </form>
    </div>
</div>
</div>



<!--  End of the form  -->
                </div>
            </div>
        </div>
    </div>
</div>
</section>
</div>


<!------------------------------------->
<!-- Javascript part of Document    --->
<!------------------------------------->

<script type="text/javascript">
var manageTableDocument;
var base_url = "<?php echo base_url(); ?>";

$(document).ready(function() {

// initialize the datatable
manageTableDocument = $('#manageTableDocument').DataTable({
    'ajax': base_url+'pending_client/fetchClientDocument/'+<?php echo $client_data['trn']; ?>
    // 'order': [[0, 'asc']]
});

});

</script>