<div class="content-wrapper">

  <section class="content-header">
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('setting') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Registration Customization</li>
    </ol>
  </section>

  <br>




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 

       <!-- Main content -->
    <section class="content">

    <div class="row">
      <div class="col-md-12 col-xs-12">

        <div id="messages"></div>

        <?php if($this->session->flashdata('success')): ?>
          <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('success'); ?>
          </div> 
        <?php elseif($this->session->flashdata('error')): ?>
          <div class="alert alert-error alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('error'); ?>
          </div>
        <?php endif; ?>

        <div class="tab-content">




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                        Q U E S T I O N                                          -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->        




      <div class="box">
          <form role="form" action="<?php base_url('requirement/update') ?>" method="post" enctype="multipart/form-data">
              <div class="box-body">

                <?php echo validation_errors(); ?>  

                <div class="row"> 

                   <div class="col-md-6 col-xs-6">
                     <div class="form-group">
                      <label for="title">Title <font color="red">*</font></label>
                      <textarea type="text" class="form-control" rows="2" id="title" name="title" autocomplete="off"><?php echo set_value('customization', isset($customization[0]['title']) ? $customization[0]['title'] : ''); ?></textarea>
                    </div>
                  </div>                

                  <div class="col-md-6 col-xs-6">
                     <div class="form-group">
                      <label for="body">Body <font color="red">*</font></label>
                      <textarea type="text" class="form-control" rows="2" id="body" name="body" autocomplete="off"><?php echo set_value('customization', isset($customization[0]['body']) ? $customization[0]['body'] : ''); ?></textarea>
                    </div>
                </div>                      
                
              </div>    <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Save Changes</button>
                <a href="<?php echo base_url('setting/') ?>" class="btn btn-warning">Close</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>






