<div class="content-wrapper">

  <section class="content-header">
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('consultation/edit') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Question</li>
    </ol>
  </section>

  <br>




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 

       <!-- Main content -->
    <section class="content">

    <div class="row">
      <div class="col-md-12 col-xs-12">

        <div id="messages"></div>

        <?php if($this->session->flashdata('success')): ?>
          <!--<div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('success'); ?>
          </div>--> 
        <?php elseif($this->session->flashdata('error')): ?>
          <div class="alert alert-error alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('error'); ?>
          </div>
        <?php endif; ?>

        <div class="tab-content">




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                        Q U E S T I O N                                          -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->        




      <div class="box">
          <form role="form" action="<?php base_url('consultation/answerQuestion') ?>" method="post" enctype="multipart/form-data">
              <div class="box-body">

                <?php echo validation_errors(); ?>  

                <div class="row"> 

                   <div class="col-md-8 col-xs-8">
                     <div class="form-group">
                        <label for="question"><?php echo $question_data['question']['question']; ?></label>
                        <?php
                            //echo ;
                            if($question_data['question']['question_type_id']==1 || $question_data['question']['question_type_id']==2)//CHECK IF QUESTION TYPE IS A TEXT OR TEXTAREA
                            {

                            }
                            elseif($question_data['question']['question_type_id']==3 || $question_data['question']['question_type_id']==4)//CHECK IF QUESTION TYPE IS A BOOLEAN OR RADIO
                            {

                            }
                            elseif($question_data['question']['question_type_id']==5)//CHECK IF QUESTION TYPE IS A DROP DOWN LIST
                            {

                            }
                            elseif($question_data['question']['question_type_id']==6)//CHECK IF QUESTION TYPE IS A CHECKBOX
                            {

                            }
                        ?>
                      
                      <textarea type="text" class="form-control" rows="1" id="response" name="response" autocomplete="off"><?php echo set_value('response', isset($question_data['question']['question']) ? $question_data['question']['question'] : ''); ?></textarea>
                    </div>
                  </div>                
                </div>    
                <br>                
              </div>    <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Save Changes</button>
                <a href="<?php echo base_url('consultation/edit') ?>" class="btn btn-warning">Close</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>


<!------------------------------------------------------------->
<!-- Javascript part of Question                                --->
<!------------------------------------------------------------->

<script type="text/javascript">  

    $(".select_group").select2();
    //$("#remark").wysihtml5();

    $("#mainQuestionNav").addClass('active');
    $("#manageQuestionNav").addClass('active');

</script>




