<div class="content-wrapper">
  <section class="content-header">
    <h1>Edit Phase </h1>
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('phase') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Phase </li>
    </ol>
  </section>


  <!-- Main content -->
  <section class="content">



<!----------------------------------------------------------------------------------------------------->
<!--                                                                                                 -->
<!--                             Error messages generated by the submit                              -->
<!--                                                                                                 -->
<!----------------------------------------------------------------------------------------------------->


    <div class="row">
      <div class="col-md-12 col-xs-12">

        <div id="messages"></div>

        <?php if($this->session->flashdata('success')): ?>
          <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('success'); ?>
          </div>
        <?php elseif($this->session->flashdata('error')): ?>
          <div class="alert alert-error alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('error'); ?>
          </div>
        <?php elseif($this->session->flashdata('warning')): ?>
          <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('warning'); ?>
          </div>
        <?php endif; ?>

        <div class="tab-content">


<!----------------------------------------------------------------------------------------------------->
<!--                                                                                                 -->
<!--                                        Session variables                                        -->
<!--                                                                                                 -->
<!----------------------------------------------------------------------------------------------------->


         <!-- Creation of a temporary session to keep the information necessary for the manipulation
              of upload of documents -->

          <?php $this->session->unset_userdata('phase_id');?>
          <?php if(empty($this->session->userdata('phase_id'))) {
                $phase_id = array('phase_id' => $phase_data['id']);
                $this->session->set_userdata($phase_id);} ?>





<!----------------------------------------------------------------------------------------------------->
<!--                                                                                                 -->
<!--                                       P H A S E                                                 -->
<!--                                                                                                 -->
<!----------------------------------------------------------------------------------------------------->


<div id="phase" class="tab-pane fade in active">

      <div class="box">
        <form role="form" action="<?php base_url('phase/update') ?>" method="post" enctype="multipart/form-data">
        <div class="box-body">

          <?php echo validation_errors(); ?>

  			  <div class="row">
      			<div class="col-md-6 col-xs-6">
              <div class="form-group">
                <label for="name">Phase Name <font color="red">*</font></label>
                <input type="text" class="form-control" id="name" name="name" autocomplete="off"
                  value="<?php echo set_value('name', isset($phase_data['name']) ? $phase_data['name'] : ''); ?>" />
              </div>
            </div>

            <div class="col-md-4 col-xs-4">
              <div class="form-group">
                <label for="code">Code <font color="red">*</font></label>
                <input type="text" class="form-control" id="code" name="code" autocomplete="off"
                value="<?php echo set_value('code', isset($phase_data['code']) ? $phase_data['code'] : ''); ?>" />
              </div>
            </div>

            <div class="col-md-2 col-xs-2">
              <div class="form-group">
                <label for="active">Active</label>
                  <div class="radio">
                    <label><input type="radio" name="active" id="active" value=1 <?php if($phase_data['active'] == 1) { echo "checked"; } ?> />
                    Active&nbsp;&nbsp;&nbsp;&nbsp;</label>
                    <label><input type="radio" name="active" id="active" value=2 <?php if($phase_data['active'] == 2) { echo "checked"; } ?> />
                    Inactive</label>
                  </div>
              </div>
            </div>
          </div>

          <div class="form-group">
            <label for="remark">Remark <font color="red">*</font></label>
            <textarea type="text" class="form-control" id="remark" name="remark" autocomplete="off">
              <?php echo set_value('remark', isset($phase_data['remark']) ? $phase_data['remark'] : ''); ?>
            </textarea>
          </div>

          <div class="row">
            <div class="col-md-4 col-xs-4">
              <div class="form-group">
                <input type="hidden" class="form-control" id="icon" name="icon"
                  value="<?php echo set_value('icon', isset($phase_data['icon']) ? $phase_data['icon'] : ''); ?>" />
                <input type="hidden" class="form-control" id="doc_type" name="doc_type"
                  value="<?php echo set_value('doc_type', isset($phase_data['doc_type']) ? $phase_data['doc_type'] : ''); ?>" />  
                <label>Upload image</label>
                <?php echo set_value('icon', isset($phase_data['icon']) ? $phase_data['icon'] : ''); ?>
                <input type="file" name="new_image" size="20" />
              </div>
            </div>
             <div class="col-md-4 col-xs-4">
                <?php if ($phase_data['icon'] <> '') : ?>
                <img src="<?php echo base_url() . '/upload/images/' . $phase_data['icon'] ?>" width="50" height="50" class="img-circle">
                <?php endif; ?>
              </div>  
             </div>

        </div> <!-- /end box -->

        <div class="box-footer">
          <button type="submit" class="btn btn-primary">Save</button>
          <a href="<?php echo base_url('phase/') ?>" class="btn btn-warning">Close</a>
        </div>

      </form>
    </div>
  </div>


<!-- Javascript part of Phase  -->

<script type="text/javascript">

  $(document).ready(function() {
    $(".select_group").select2();
    $("#remark").wysihtml5();

    $("#mainPhaseNav").addClass('active');
    $("#managePhaseNav").addClass('active');

  });
</script>







<!--  End of the form  -->
      </div>
    </div>
  </div>
</section>
</div>






