<div class="content-wrapper">

<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 

       <!-- Main content -->
    <section class="content">

    <div class="row">
      <div class="col-md-12 col-xs-12">

        <div id="messages"></div>

        <?php if($this->session->flashdata('success')): ?>
          <!--<div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('success'); ?>
          </div>--> 
        <?php elseif($this->session->flashdata('error')): ?>
          <div class="alert alert-error alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('error'); ?>
          </div>
        <?php endif; ?>

        <div class="tab-content">




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                        Q U E S T I O N                                          -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->        




      <div class="box">
          <form role="form" action="<?php base_url('consultation/answerQuestion') ?>" method="post" enctype="multipart/form-data">
              <div class="box-body">

                <?php echo validation_errors(); ?>  

                <div class="row"> 

                   <div class="col-md-8 col-xs-8">
                     <div class="form-group">
                        <br>
                        <label for="question"><?php echo $question_data['question']['question']; ?></label>
                        <br>
                        <?php
                            //echo ;
                            if($question_data['question']['question_type_id']==1 || $question_data['question']['question_type_id']==2)//CHECK IF QUESTION TYPE IS A TEXT OR TEXTAREA
                            {
                                echo"
                                    <textarea style='overflow:auto;resize:none' class='form-control' rows='1' name='response".'[]'."' value=''></textarea>
                                ";
                            }
                            elseif($question_data['question']['question_type_id']==3 || $question_data['question']['question_type_id']==4)//CHECK IF QUESTION TYPE IS A BOOLEAN OR RADIO
                            {
                                if(array_key_exists('question_option', $question_data) && !empty($question_data['question_option']))
                                {
                                    foreach($question_data['question_option'] as $option)
                                    {
                                        ?>
                                        <div class="radio">
                                            <label>
                                                <input type="radio" name="response[]" value="<?php echo $option['id']?>"><?php echo $option['ques_option'];?>
                                                <br>
                                            </label>
                                        </div>
                                        <?php
                                    }                                    
                                }
                            }
                            elseif($question_data['question']['question_type_id']==5)//CHECK IF QUESTION TYPE IS A DROP DOWN LIST
                            {
                              if(array_key_exists('question_option', $question_data) && !empty($question_data['question_option']))
                              {
                                echo"
                                  <select class='form-control select_group' name='response".'[]'."'>
                                    <option value='' name='response".'[]'."' selected>Select One</option>";
                                    foreach($question_data['question_option'] as $option)
                                    {
                                      ?>
                                      <option name="response[]" value="<?php echo $option['id'];?>"><?php echo $option['ques_option'];?></option>
                                      <?php
                                    }
                                  echo"
                                  </select>
                                ";
                              }
                            }
                            elseif($question_data['question']['question_type_id']==6)//CHECK IF QUESTION TYPE IS A CHECKBOX
                            {
                              if(array_key_exists('question_option', $question_data) && !empty($question_data['question_option']))
                              {
                                foreach($question_data['question_option'] as $option)
                                {
                                    ?>
                                    <div class='form-check'>
                                    <input type='checkbox' class="form-check-input" name='response[]' value='<?php echo $option['id'];?>'>
                                        <label class="form-check-label"><?php echo $option['ques_option'];?></label>
                                    </div>
                                  <?php
                                }
                              }                                
                            }
                        ?>
                    </div>
                  </div>                
                </div>                   
              </div>    <!-- /.box-body -->

              <div class="box-footer">
              <?php if(in_array('updateAnswers', $user_permission)): ?>
                <button type="submit" class="btn btn-primary">Save Changes</button>
              <?php endif; ?>
                <a href="<?php echo base_url('consultation/update/'.$consultationId); ?>" class="btn btn-warning">Close</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>







