<div class="content-wrapper">

  <section class="content-header">
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('question') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Question</li>
    </ol>
  </section>

  <br>




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 

       <!-- Main content -->
    <section class="content">

    <div class="row">
      <div class="col-md-12 col-xs-12">

        <div id="messages"></div>

        <?php if($this->session->flashdata('success')): ?>
          <!--<div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('success'); ?>
          </div>--> 
        <?php elseif($this->session->flashdata('error')): ?>
          <div class="alert alert-error alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('error'); ?>
          </div>
        <?php endif; ?>

        <div class="tab-content">




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                        Q U E S T I O N                                          -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->        




      <div class="box">
          <form role="form" action="<?php base_url('question/update') ?>" method="post" enctype="multipart/form-data">
              <div class="box-body">

                <?php echo validation_errors(); ?>  

                 <div class="row">

                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="standard">Standard</label>
                      <select class="form-control select_group" id="standard" name="standard">
                        <option value=""></option> 
                        <?php foreach ($standard as $k => $v): ?>
                          <option value="<?php echo $v['id'] ?>" <?php if($question_data['question']['standard_id'] == $v['id']) { echo "selected='selected'"; } ?> ><?php echo $v['name'] ?></option>
                        <?php endforeach ?>
                     </select>
                    </div>
                  </div> 

                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="clause">Clause</label>
                      <select class="form-control select_group" id="clause" name="clause">
                        <option value=""></option> 
                        <?php foreach ($clause as $k => $v): ?>
                          <option value="<?php echo $v['id'] ?>" <?php if($question_data['question']['clause_id'] == $v['id']) { echo "selected='selected'"; } ?> ><?php echo $v['name'] ?></option>
                        <?php endforeach ?>
                     </select>
                    </div>
                  </div> 

                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="sub_clause">Sub Clause</label>
                      <select class="form-control select_group" id="sub_clause" name="sub_clause">
                        <option value=""></option> 
                        <?php foreach ($sub_clause as $k => $v): ?>
                          <option value="<?php echo $v['id'] ?>" <?php if($question_data['question']['sub_clause_id'] == $v['id']) { echo "selected='selected'"; } ?> ><?php echo $v['code'].' - '.$v['name'] ?></option>
                        <?php endforeach ?>
                     </select>
                    </div>
                  </div> 

                  <div class="col-md-2 col-xs-2" align="left">
                    <div class="radio">
                      <label><input type="radio" name="active" id="active" class="" <?php if($question_data['question']['active']=='1') echo "checked='checked'"; ?> value="1" <?php echo $this->form_validation->set_radio('active', 1); ?> />Active&nbsp;&nbsp;&nbsp;&nbsp;</label>
                      <label><input type="radio" name="active" id="active" class="" <?php if($question_data['question']['active']=='2') echo "checked='checked'"; ?> value="2" <?php echo $this->form_validation->set_radio('active', 2); ?> />Inactive</label> 
                    </div>
                  </div>

                </div> 

                  

                <div class="row"> 

                   <div class="col-md-6 col-xs-6">
                     <div class="form-group">
                      <label for="question">Question</label>
                      <textarea type="text" class="form-control" rows="5" id="question" name="question" autocomplete="off"><?php echo set_value('question', isset($question_data['question']['question']) ? $question_data['question']['question'] : ''); ?></textarea>
                    </div>
                  </div>                

                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="question_type">Question Type <font color="red">*</font></label>
                      <select class="form-control select_group" id="question_type" name="question_type">
                        <option value=""></option> 
                        <?php foreach ($question_type as $k => $v): ?>
                          <option value="<?php echo $v['id'] ?>" 
                          <?php if(set_value('question_type', isset($question_data['question']['question_type_id']) ? $question_data['question']['question_type_id'] : '') == $v['id']) { echo "selected='selected'"; } ?> >
                          <?php echo $v['name'] ?>                            
                          </option>
                        <?php endforeach ?>
                      </select>
                    </div>
                  </div>

                  <div class="col-md-1 col-xs-1" align="left">
                    <div class="radio">
                      <label><input type="radio" name="upload_document" id="upload_document" class="" <?php if($question_data['question']['upload_document']=='1') echo "checked='checked'"; ?> value="1" <?php echo $this->form_validation->set_radio('upload_document', 1); ?> />Upload&nbsp;&nbsp;&nbsp;&nbsp;</label>
                      <br>
                      <label><input type="radio" name="upload_document" id="upload_document" class="" <?php if($question_data['question']['upload_document']=='2') echo "checked='checked'"; ?> value="2" <?php echo $this->form_validation->set_radio('upload_document', 2); ?> />No Upload</label> 
                    </div>
                  </div>

                  <div class="col-md-2 col-xs-2" align="left">
                    <div class="radio">
                      <label><input type="radio" name="choice" id="choice" class="" <?php if($question_data['question']['choice']=='1') echo "checked='checked'"; ?> value="1" <?php echo $this->form_validation->set_radio('choice', 1); ?> />One Choice&nbsp;&nbsp;&nbsp;&nbsp;</label>
                      <br>
                      <label><input type="radio" name="choice" id="choice" class="" <?php if($question_data['question']['choice']=='2') echo "checked='checked'"; ?> value="2" <?php echo $this->form_validation->set_radio('choice', 2); ?> />Multiple Choice</label> 
                    </div>
                  </div>

                </div>    


  				  
 
        <table class="table table-bordered" id="option_info_table">
            <thead>
              <tr>
                <th style="width:30%">Option <font color="red">*</font></th>
                <th style="width:10%">
                  <button type="button" id="add_row" class="btn btn-default"><i class="fa fa-plus"></i></button></th>
              </tr>
            </thead>

            <tbody>

              <?php if(isset($question_data['question_option'])): ?>
                <?php $x = 1; ?>
                <?php foreach ($question_data['question_option'] as $key => $val): ?>
                 <tr id="row_<?php echo $x; ?>">
                     <td><input type="text" name="option[]" id="option_<?php echo $x; ?>" class="form-control" required value="<?php echo $val['option_desc'] ?>" autocomplete="off"></td>

                    <td><button type="button" class="btn btn-default" onclick="removeRow('<?php echo $x; ?>')"><i class="fa fa-close"></i></button></td>
                 </tr>
                 <?php $x++; ?>
               <?php endforeach; ?>
             <?php else: ?>  <!-- We insert a blank line -->

                      <tr id="row_1">
                        <td><input type="text" name="option[]" id="option_1" class="form-control" ></td>                
                        <td><button type="button" class="btn btn-default" onclick="removeRow('1')"><i class="fa fa-close"></i></button></td>
                     </tr>

             <?php endif; ?>
             </tbody>
          </table>


 
                <br>
              
                <div class="row">  
        
                  <div class="col-md-12 col-xs-12">
                     <div class="form-group">
                      <label for="remark">Remark</label>
                      <textarea type="text" class="form-control" rows="5" id="remark" name="remark" autocomplete="off"><?php echo set_value('remark', isset($question_data['question']['remark']) ? $question_data['question']['remark'] : ''); ?></textarea>
                    </div>
                  </div>  
                </div>  
                
              </div>    <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Save Changes</button>
                <a href="<?php echo base_url('question/') ?>" class="btn btn-warning">Close</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>


<!------------------------------------------------------------->
<!-- Javascript part of Question                                --->
<!------------------------------------------------------------->

<script type="text/javascript">  

    $(".select_group").select2();
    //$("#remark").wysihtml5();

    $("#mainQuestionNav").addClass('active');
    $("#manageQuestionNav").addClass('active');
    
    
function removeRow(tr_id)
    {
    $("#option_info_table tbody tr#row_"+tr_id).remove();

    }


  // Add new row in the table
    $("#add_row").unbind('click').bind('click', function() {
      var table = $("#option_info_table");
      var count_table_tbody_tr = $("#option_info_table tbody tr").length;
      var row_id = count_table_tbody_tr + 1;

      $.ajax({
          success:function(response) {

               var html = '<tr id="row_'+row_id+'">'+
                   
                    '<td><input type="text" name="option[]" id="option_'+row_id+'" class="form-control" </td>'+

                    '<td><button type="button" class="btn btn-default" onclick="removeRow(\''+row_id+'\')"><i class="fa fa-close"></i></button></td>'+
                    '</tr>';

                if(count_table_tbody_tr >= 1) {$("#option_info_table tbody tr:last").after(html);}
                else {$("#option_info_table tbody").html(html);}

                $(".option").select2(); }
              });

      return false;   });


</script>




