<div class="content-wrapper">

  <section class="content-header">
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('program') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Program</li>
    </ol>
  </section>

  <br>




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 

       <!-- Main content -->
    <section class="content">

    <div class="row">
      <div class="col-md-12 col-xs-12">

        <div id="messages"></div>

        <?php if($this->session->flashdata('success')): ?>
          <!--<div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('success'); ?>
          </div>--> 
        <?php elseif($this->session->flashdata('error')): ?>
          <div class="alert alert-error alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('error'); ?>
          </div>
        <?php endif; ?>

        <div class="tab-content">




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                        Q U E S T I O N                                          -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->        




      <div class="box">
          <form role="form" action="<?php base_url('program/update') ?>" method="post" enctype="multipart/form-data">
              <div class="box-body">

                <?php echo validation_errors(); ?>  

                 <div class="row">

                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="standard">Standard</label>
                      <select class="form-control select_group" id="standard" name="standard">
                        <option value=""></option> 
                        <?php foreach ($standard as $k => $v): ?>
                          <option value="<?php echo $v['id'] ?>" <?php if($program_data['program']['standard_id'] == $v['id']) { echo "selected='selected'"; } ?> ><?php echo $v['name'] ?></option>
                        <?php endforeach ?>
                     </select>
                    </div>
                  </div> 

                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="clause">Clause</label>
                      <select class="form-control select_group" id="clause" name="clause">
                        <option value=""></option> 
                        <?php foreach ($clause as $k => $v): ?>
                          <option value="<?php echo $v['id'] ?>" <?php if($program_data['program']['clause_id'] == $v['id']) { echo "selected='selected'"; } ?> ><?php echo $v['name'] ?> - <?php echo $v['standard_name'] ?></option>
                        <?php endforeach ?>
                     </select>
                    </div>
                  </div> 

                  <div class="col-md-2 col-xs-2" align="left">
                    <div class="radio">
                      <label><input type="radio" name="active" id="active" class="" <?php if($program_data['program']['active']=='1') echo "checked='checked'"; ?> value="1" <?php echo $this->form_validation->set_radio('active', 1); ?> />Active&nbsp;&nbsp;&nbsp;&nbsp;</label>
                      <label><input type="radio" name="active" id="active" class="" <?php if($program_data['program']['active']=='2') echo "checked='checked'"; ?> value="2" <?php echo $this->form_validation->set_radio('active', 2); ?> />Inactive</label> 
                    </div>
                  </div>

                </div> 

                  

                <div class="row"> 

                   <div class="col-md-6 col-xs-6">
                     <div class="form-group">
                      <label for="program_name">Program name</label>
                      <textarea type="text" class="form-control" rows="5" id="program_name" name="program_name" autocomplete="off"><?php echo set_value('program_name', isset($program_data['program']['program_name']) ? $program_data['program']['program_name'] : ''); ?></textarea>
                    </div>
                  </div>  

                </div>    


  				  
 
        <table class="table table-bordered" id="phase_info_table">
                  <thead>
                    <tr>
                      <th style="width:50%">Phase</th>                     
                      <th style="width:10%"><button type="button" id="add_row" class="btn btn-default"><i class="fa fa-plus"></i></button></th>
                    </tr>
                  </thead>

                  <tbody>

                    <?php if(isset($program_data['program_phase'])): ?>
                      <?php $x = 1; ?>
                      <?php foreach ($program_data['program_phase'] as $key => $val): ?>                        
                       <tr id="row_<?php echo $x; ?>">
                         <td>
                          <select class="form-control select_group phase" data-row-id="row_<?php echo $x; ?>" id="phase_<?php echo $x; ?>" name="phase[]" style="width:100%;" >
                              <option value=""></option>
                              <?php foreach ($phase as $k => $v): ?>
                                <option value="<?php echo $v['id'] ?>" <?php if($val['phase_id'] == $v['id']) { echo "selected='selected'"; } ?>><?php echo $v['name'] ?></option>
                              <?php endforeach ?>
                            </select>
                          </td>
                        
                          <td><button type="button" class="btn btn-default" onclick="removeRow('<?php echo $x; ?>')"><i class="fa fa-close"></i></button></td>
                       </tr>
                       <?php $x++; ?>
                     <?php endforeach; ?>
     
                   <?php else: ?>  <!-- We insert a blank line -->

                      <tr id="row_1">
                       <td>
                        <select class="form-control select_group phase" data-row-id="row_1" id="phase_1" name="phase[]" style="width:100%;" >
                            <option value=""></option>
                            <?php foreach ($phase as $k => $v): ?>
                              <option value="<?php echo $v['id'] ?>"><?php echo $v['name'] ?></option>
                            <?php endforeach ?>
                          </select>
                        </td>                     
                        <td><button type="button" class="btn btn-default" onclick="removeRow('1')"><i class="fa fa-close"></i></button></td>
                     </tr>

                   <?php endif; ?>
                   </tbody>
                </table>


 
                <br>
              
                <div class="row">  
        
                  <div class="col-md-12 col-xs-12">
                     <div class="form-group">
                      <label for="remark">Remark</label>
                      <textarea type="text" class="form-control" rows="5" id="remark" name="remark" autocomplete="off"><?php echo set_value('remark', isset($program_data['program']['remark']) ? $program_data['program']['remark'] : ''); ?></textarea>
                    </div>
                  </div>  
                </div>  
                
              </div>    <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Save Changes</button>
                <a href="<?php echo base_url('program/') ?>" class="btn btn-warning">Close</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>


<!------------------------------------------------------------->
<!-- Javascript part of Program                                --->
<!------------------------------------------------------------->

<script type="text/javascript">  

    $(".select_group").select2();
    //$("#remark").wysihtml5();

    $("#mainProgramNav").addClass('active');
    $("#manageProgramNav").addClass('active');
    
    
function removeRow(tr_id)
    {
    $("#phase_info_table tbody tr#row_"+tr_id).remove();

    }


  // Add new row in the table 
    $("#add_row").unbind('click').bind('click', function() {
      var table = $("#phase_info_table");
      var count_table_tbody_tr = $("#phase_info_table tbody tr").length;      
      var row_id = count_table_tbody_tr + 1;

      $.ajax({
          success:function(response) {            

               var html = '<tr id="row_'+row_id+'">'+
                   '<td>'+ 

                     '<select class="form-control select_group phase" data-row-id="'+row_id+'" id="phase_1" name="phase[]" style="width:100%;" >' +
                            '<option value=""></option>' +
                            '<?php foreach ($phase as $k => $v): ?>' +
                             '<option value="<?php echo $v['id'] ?>"><?php echo $v['name'] ?></option>' +
                             '<?php endforeach ?>' ;

                      html += '</select>'+
                    '</td>'+                  
                    '<td><button type="button" class="btn btn-default" onclick="removeRow(\''+row_id+'\')"><i class="fa fa-close"></i></button></td>'+
                    '</tr>';

                if(count_table_tbody_tr >= 1) {$("#phase_info_table tbody tr:last").after(html);}
                else {$("#phase_info_table tbody").html(html);}

                $(".phase").select2(); }
              });

      return false;   });


</script>




